### ISSUE TITLE
Bug with blank lines being deleted by autofixer

### ISSUE THREAD

**Issue by msridhar** [nimakarimipour/Diagnoser#10]
@lazaroclapp has observed this problem on Uber code.  If we can get an example to reproduce it, we will investigate.

**Comment by nimakarimipour** [comment]
I provided the test case [here](https://github.com/nimakarimipour/Diagnoser/tree/main/tests/units/whiteline), where currently the test passes and no white line is removed. Also ```goJF``` is now executed after every run of unit test before doing any comparison.
