### ISSUE TITLE
Wrong Initializers

### ISSUE THREAD

**Issue by nimakarimipour** [nimakarimipour/Diagnoser#4]
Our current algorithm for detecting `@Initializers` is not working correctly. For the example below:

Case 1:
```java
int foo() {
  if (this.bar == null) { throw new RuntimeException("whoops"); }
  return 0;
}
```
We mistakenly mark `foo` as @Initializer since it guarantees `bar` to be `@Nonnull` which is clearly is not enough.

Another example of wrong injection:

Case 2:
```java
public abstract class B {
   protected Baz foo;
   
   @Initializer // Added by tool
   public boolean isBar() {
     return this.foo == Baz.Bar; // where Baz is an enum
   }
}

class A extents B {
   public A(...) {
      ...
      this.foo = [...] // non-null expr
   }
}
```

Suggestion from @msridhar for Case 1:

Check that a non-null value is written to the class field.

**Comment by msridhar** [comment]
It would be good to understand the root cause for the second example.  I don't immediately see why we would infer `@Initializer` for that case.
