### ISSUE TITLE
Configurable Path

### ISSUE THREAD

**Issue by nimakarimipour** [nimakarimipour/Diagnoser#5]
Make paths configurable in all  ```NullAwayAutoFixer``` artifacts.

**Comment by nimakarimipour** [comment]
Helle all, @msridhar @lazaroclapp 

I have made paths configurable in NullAway and it can be set via a flag ```-XepOpt:NullAway:AutoFixOutPutDirectory```. The default path is ```/tmp/NullAwayFix``` if not specified. 

However, both scripts in python and NullAway need to know the path of the output directory. And we have to hardcode the value in both ```build.gradle``` and ```config``` file of the scripts. If that seems reasonble to you please let me know and I will close this issue. Thank you.

With best regards

**Comment by lazaroclapp** [comment]
I would strongly prefer if there wasn't a global path, even as a default. Can we just make the checker fail with a configuration error if run with the autofix flag on and without an explicit value for `-XepOpt:NullAway:AutoFixOutPutDirectory`?

Also, reminder that another thing that needs to happen is that directory being write-only from the point of view of NullAway, and non-persistent from the point of view of the external toolchain, so the python scripts probably still need another directory to copy ongoing working data to (with the idea being that the `AutoFixOutPutDirectory` is cleared between compilations).

**Comment by nimakarimipour** [comment]
> I would strongly prefer if there wasn't a global path, even as a default. Can we just make the checker fail with a configuration error if run with the autofix flag on and without an explicit value for `-XepOpt:NullAway:AutoFixOutPutDirectory`?
> 
> Also, reminder that another thing that needs to happen is that directory being write-only from the point of view of NullAway, and non-persistent from the point of view of the external toolchain, so the python scripts probably still need another directory to copy ongoing working data to (with the idea being that the `AutoFixOutPutDirectory` is cleared between compilations).

Ok sure will do that, I will apply these changes now. Thank you.

**Comment by nimakarimipour** [comment]
> I would strongly prefer if there wasn't a global path, even as a default. Can we just make the checker fail with a configuration error if run with the autofix flag on and without an explicit value for `-XepOpt:NullAway:AutoFixOutPutDirectory`?
> 
> Also, reminder that another thing that needs to happen is that directory being write-only from the point of view of NullAway, and non-persistent from the point of view of the external toolchain, so the python scripts probably still need another directory to copy ongoing working data to (with the idea being that the `AutoFixOutPutDirectory` is cleared between compilations).

Hi @lazaroclapp, I have one question regarding configurable paths. Both script and NullAway should be informed about the output directory to interact with each other. In Gradle projects we can pass it via setting this flag ```-XepOpt:NullAway:AutoFixOutPutDirectory``` in ```tasks.withType(JavaCompile)``` function in ```build.gradle``` file and also should configure path in the python script. These two directories should be set in two places rather than only once place. Even if I find a way to automatically modify ```build.gradle``` files with python script, I am not sure how we can do it at Uber. Would you please tell me how we can address this issue or we can temporarily move forward with the current situation.
