### ISSUE TITLE
Find a Universal Printer

### ISSUE THREAD

**Issue by nimakarimipour** [nimakarimipour/Diagnoser#9]
Experiment using latest version of ```javaparser``` across all projects and log errors.

**Comment by nimakarimipour** [comment]
Fixes have been applied to the version on GitHub, not on MavenCentral.

**Comment by msridhar** [comment]
@nimakarimipour can't you test with a snapshot build of javaparser, before the next release?  that way, if we find more bugs, we can report them and maybe get those fixes included before the next release

**Comment by nimakarimipour** [comment]
> @nimakarimipour can't you test with a snapshot build of javaparser, before the next release? that way, if we find more bugs, we can report them and maybe get those fixes included before the next release

Hi @Manu, I actually did that. I tested it with the ```3.23.2-SNAPSHOT``` which is the current version on Github and I ran it across all our benchmarks with ```depth -1``` which injects every fix regardless of it's effect and did not see any failure by ```LexicalPreservationPrinter```. Their version on Github seems pretty stable and I am looking for the new version to be uploaded on ```MavenCentral```.

**Comment by msridhar** [comment]
That's awesome news!  So it looks like this issue will be solved once they cut a new release.  Thanks!

**Comment by msridhar** [comment]
BTW, if we are otherwise ready with a bunch of improvements and are just waiting on their release, I think we should just go ahead and change our code to depend on a `LOCAL` version of javaparser.

**Comment by nimakarimipour** [comment]
> BTW, if we are otherwise ready with a bunch of improvements and are just waiting on their release, I think we should just go ahead and change our code to depend on a `LOCAL` version of javaparser.

Ok sure, I will make a version with ```git tag``` of ```javaparser``` and add it to ```injector```.

**Comment by nimakarimipour** [comment]
Closing this issue, since version ```3.24.0``` is released in ```mavencentral``` and upgraded ```injector``` to use this version. https://github.com/nimakarimipour/Injector/commit/a72367bd08ed274b515e6a0ff52f0b33724aaa1e
